import type React from "react"
import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import Link from "next/link"
import { LogoMark } from "@/components/logo-mark"
import { Avatar } from "@/components/ui/avatar"
import { NavLink } from "@/components/nav-links"
import { LogIn } from "lucide-react"
import { ThemeToggle } from "@/components/theme-toggle"
import { MobileNav } from "@/components/mobile-nav"
import { createClient } from "@/utils/supabase/server"
import FooterNav from "@/components/footer-nav"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const supabase = await createClient()
  const { data } = await supabase.auth.getUser()
  const user = data.user

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}>
        <header className="w-full border-b border-black/10">
          <nav className="px-2 h-16 flex items-center justify-between relative">
            <div className="flex items-center gap-2">
              <Link href="/" className="mr-2 inline-flex items-center gap-2" aria-label="Limpopo Chess Academy">
                <LogoMark className="h-8 w-auto sm:h-10 md:h-12" />
              </Link>
              <div className="hidden md:flex items-center gap-1">
                {user ? (
                  <NavLink href="/user/profile" color="primary">
                    My Profile
                  </NavLink>
                ) : null}
                {user ? (
                  <NavLink href="/user/user-dashboard" color="secondary">
                    User Dashboard
                  </NavLink>
                ) : null}
                {user ? (
                  <NavLink href="/admin/admin-dashboard" color="gray">
                    Admin Dashboard
                  </NavLink>
                ) : null}
                {user ? (
                  <NavLink href="/admin/upload-tournament" color="gray">
                    Upload Tournament
                  </NavLink>
                ) : null}
                <NavLink href="/tournaments" color="gray">
                  Tournaments
                </NavLink>
                <NavLink href="/rankings" color="gray">
                  Rankings
                </NavLink>
                <NavLink href="/players" color="gray">
                  Players
                </NavLink>
                <NavLink href="/forms" color="gray">
                  Forms
                </NavLink>
              </div>
            </div>
            <div className="flex items-center gap-2 flex-shrink-0">
              <ThemeToggle />
              <MobileNav isAuthenticated={Boolean(user)} />
              {user ? (
                <form
                  action={async () => {
                    "use server"
                    const server = await createClient()
                    await server.auth.signOut()
                  }}
                >
                  <div className="flex items-center gap-2">
                    <Avatar name={user.email ?? "User"} />
                    <span className="text-sm text-neutral-700 dark:text-neutral-200 hidden lg:inline max-w-32 truncate">
                      {user.email}
                    </span>
                    <button
                      className="text-xs rounded-md border px-2 py-1 hover:bg-neutral-50 dark:hover:bg-white/10 focus-visible:ring-2 focus-visible:ring-offset-2 whitespace-nowrap"
                      type="submit"
                    >
                      Sign out
                    </button>
                  </div>
                </form>
              ) : (
                <>
                  <Link
                    href="/login"
                    className="text-xs rounded-md border px-2 py-1 hover:bg-neutral-50 dark:hover:bg-white/10 focus-visible:ring-2 focus-visible:ring-offset-2 inline-flex items-center gap-1"
                  >
                    <LogIn className="h-3 w-3" aria-hidden />
                    <span className="opacity-60 cursor-not-allowed select-none" aria-disabled="true">
                      Login
                    </span>
                  </Link>
                  <span
                    className="text-xs rounded-md border px-2 py-1 opacity-60 cursor-not-allowed select-none inline-flex items-center gap-1"
                    aria-disabled="true"
                  >
                    Sign Up
                  </span>
                </>
              )}
            </div>
          </nav>
        </header>
        <main className="flex-1">{children}</main>
        <FooterNav />
      </body>
    </html>
  )
}
